# Generated by Django 4.2.6 on 2023-10-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('Author_Id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Isbn', models.CharField(max_length=15, primary_key='True', serialize=False)),
                ('Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.authors')),
                ('Isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
            options={
                'unique_together': {('Author_Id', 'Isbn')},
            },
        ),
    ]
