# Generated by Django 4.2.6 on 2023-10-21 17:27

from django.db import migrations, models

def set_initial_card_id(apps, schema_editor):
    YourModel = apps.get_model('books', 'Borrowers')  

    YourModel.objects.create(card_id='ID000001') 

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_id_authors_author_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=11)),
                ('borrower_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RunPython(set_initial_card_id),
    ]
