# Generated by Django 4.2.6 on 2023-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowers',
        ),
    ]
