# Generated by Django 4.2.6 on 2023-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_borrowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=11)),
                ('borrower_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
