# Generated by Django 4.2.6 on 2023-10-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowers',
            name='card_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
