# Generated by Django 4.2.6 on 2023-10-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_borrowers_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowers',
            name='ssn',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
