# Generated by Django 4.2.6 on 2023-10-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_borrowers_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField()),
                ('due_date', models.DateField()),
                ('date_in', models.DateField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrowers')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
    ]
