# Generated by Django 4.2.6 on 2023-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookloans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='date_in',
            field=models.DateField(default=None),
        ),
    ]
