# Generated by Django 4.2.6 on 2023-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookloans_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='date_in',
            field=models.DateField(null=True),
        ),
    ]
