# Generated by Django 4.2.6 on 2023-10-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_bookavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amt', models.FloatField(max_length=2)),
                ('paid', models.IntegerField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookloans')),
            ],
        ),
    ]
