# Generated by Django 4.2.6 on 2023-10-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_fines_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookauthors',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookauthors',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='bookauthors',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='bookavailability',
            name='borrowed_by',
        ),
        migrations.RemoveField(
            model_name='bookavailability',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='bookloans',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='bookloans',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='loan_id',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='BookAuthors',
        ),
        migrations.DeleteModel(
            name='BookAvailability',
        ),
        migrations.DeleteModel(
            name='BookLoans',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Borrowers',
        ),
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
